unit7 = {
    "Tourism": [

        ("accommodation","konaklama"),
        ("all inclusive","her şey dahil"),
        ("all inclusive hotels","her şey dahil oteller"),
        ("amazing","harika"),
        ("amphitheatre","amfitiyatro"),
        ("ancient","antik"),
        ("ancient cities","antik şehirler"),
        ("architecture","mimari"),
        ("ash","kül"),
        ("attraction","cazibe merkezi"),
        ("attractive","çekici"),
        ("beautiful","güzel"),
        ("bed and breakfast","oda ve kahvaltı"),
        ("been to","bulunmuş olmak"),
        ("begin","başlamak"),
        ("big","büyük"),
        ("book","rezervasyon yapmak"),
        ("book a room","oda ayırtmak"),
        ("both","her ikisi"),
        ("build","inşa etmek"),
        ("building","bina"),
        ("busy","meşgul"),
        ("busy street","kalabalık cadde"),
        ("buy souvenir","hediyelik eşya almak"),
        ("cheap","ucuz"),
        ("clean","temiz"),
        ("comfortable","rahat"),
        ("compare","karşılaştırmak"),
        ("concert","konser"),
        ("country","ülke, kırsal bölge"),
        ("countryside","kırsal bölge"),
        ("cover","kaplamak"),
        ("crowded","kalabalık"),
        ("cruise","gemi seyahati"),
        ("destination","varış yeri"),
        ("detail","detay"),
        ("die","ölmek"),
        ("different","farklı"),
        ("dirty","kirli"),
        ("dull","sıkıcı"),
        ("earthquake","deprem"),
        ("enjoy trip","yolculuktan keyif almak"),
        ("enjoyable","keyifli"),
        ("entertain","eğlendirmek"),
        ("entertainment","eğlence"),
        ("escape","kaçmak"),
        ("excited","heyecanlı"),
        ("expedition","keşif gezisi"),
        ("expensive","pahalı"),
        ("famous","ünlü"),
        ("famous square","ünlü meydan"),
        ("fascinating","büyüleyici"),
        ("feel","hissetmek"),
        ("fountain","çeşme"),
        ("golden beaches","altın kumsallar"),
        ("gorgeous","muhteşem"),
        ("guess","tahmin etmek"),
        ("happen","olmak"),
        ("have a rest","dinlenmek"),
        ("heritage","miras"),
        ("historic site","tarihi alan"),
        ("historical","tarihi"),
        ("history","tarih"),
        ("hope","umut"),
        ("hospitable","misafirperver"),
        ("how long","ne kadar süre"),
        ("huge","kocaman"),
        ("imagine","hayal etmek"),
        ("in my opinion","benim fikrimce"),
        ("incredible","inanılmaz"),
        ("interesting things","ilginç şeyler"),
        ("invite","davet etmek"),
        ("island","ada"),
        ("keep","tutmak"),
        ("kind","nazik"),
        ("learn","öğrenmek"),
        ("leave","ayrılmak"),
        ("local dish","yerel yemek"),
        ("location","konum"),
        ("lovely","sevimli"),
        ("lying in the sun","güneşin altında uzanmak"),
        ("make wish","dilek tutmak"),
        ("mysterious","gizemli"),
        ("natural","doğal"),
        ("noisy","gürültülü"),
        ("offer","teklif etmek"),
        ("old building","eski bina"),
        ("opinion","fikir"),
        ("organize","organize etmek"),
        ("painting","tablo"),
        ("palace","saray"),
        ("perfect","mükemmel"),
        ("place","yer"),
        ("port city","liman şehri"),
        ("public","halka açık"),
        ("quiet","sessiz"),
        ("ready","hazır"),
        ("relaxing","rahatlatıcı"),
        ("religious celebration","dini kutlama"),
        ("resort","tatil köyü"),
        ("rich","zengin"),
        ("rural","kırsal"),
        ("sail","yelken açmak"),
        ("school trip","okul gezisi"),
        ("sightseeing tour","gezi turu"),
        ("soil","toprak"),
        ("souvenir","hediyelik eşya"),
        ("spend","harcamak"),
        ("square","meydan"),
        ("stay","kalmak"),
        ("sunbathe","güneşlenmek"),
        ("taste","tatmak"),
        ("taste local dishes","yerel yemekleri tatmak"),
        ("teach tradition","geleneği öğretmek"),
        ("tell","söylemek"),
        ("temple","tapınak"),
        ("terrible","korkunç"),
        ("theatre","tiyatro"),
        ("tiring","yorucu"),
        ("to me","bana göre"),
        ("together","birlikte"),
        ("tourist attraction","turistik cazibe merkezi"),
        ("town","kasaba"),
        ("tradition","gelenek"),
        ("traditional","geleneksel"),
        ("traditional dish","geleneksel yemek"),
        ("transportation","ulaşım"),
        ("travel","seyahat etmek"),
        ("trip","gezi"),
        ("try","denemek"),
        ("unbelievable","inanılmaz"),
        ("urban","kentsel"),
        ("water pipeline","su boru hattı"),
        ("weather","hava durumu"),
        ("which","hangi"),
        ("wild life","vahşi yaşam"),
        ("world","dünya"),
        ("would rather","tercih etmek")

    ]
}
