unit4 = {
    "On The Phone": [

        ("answer","cevap vermek"),
        ("application","uygulama"),
        ("appointment","randevu"),
        ("arrange","ayarlamak"),
        ("ask","sormak"),
        ("at the moment","şu anda"),
        ("available","müsait"),
        ("begin","başlamak"),
        ("call","aramak, çağrı"),
        ("caller","arayan kişi"),
        ("can I","yapabilir miyim"),
        ("cell phone","cep telefonu"),
        ("change","değiştirmek"),
        ("communication","iletişim"),
        ("company employee","şirket çalışanı"),
        ("concert hall","konser salonu"),
        ("connection","bağlantı"),
        ("contact","iletişime geçmek"),
        ("conversation","konuşma"),
        ("could you …","yapabilir misiniz"),
        ("delivery","teslimat"),
        ("device","cihaz"),
        ("dial a number","numara çevirmek"),
        ("dial","tuşlamak"),
        ("different","farklı"),
        ("discover","keşfetmek"),
        ("each other","birbirine"),
        ("engaged","meşgul"),
        ("experimental","deneysel"),
        ("extension number","dahili numara"),
        ("fast","hızlı"),
        ("feel better","daha iyi hissetmek"),
        ("fine","iyi"),
        ("get back","geri dönmek"),
        ("get well soon","geçmiş olsun"),
        ("get","almak"),
        ("give","vermek"),
        ("graduation","mezuniyet"),
        ("great","harika"),
        ("guess","tahmin etmek"),
        ("habit","alışkanlık"),
        ("hang on","beklemek"),
        ("headquarter","genel merkez"),
        ("hear","duymak"),
        ("here","burada"),
        ("hold on","beklemek"),
        ("how often","ne sıklıkla"),
        ("I guess","sanırım"),
        ("I’ll get him","telefonu ona veriyorum/çağırıyorum"),
        ("I’ll take that","(telefonu)ben açarım"),
        ("I’m afraid","korkarım ki"),
        ("I’m sorry to hear that","bunu duyduğuma üzüldüm"),
        ("ill","hasta"),
        ("imagine","hayal etmek"),
        ("interviewer","röportajcı"),
        ("invented","icat edilmiş"),
        ("invention","icat"),
        ("journal","dergi"),
        ("just a minute","bir dakika"),
        ("keep in touch","iletişimde kalmak"),
        ("learn","öğrenmek"),
        ("leave","ayrılmak, bırakmak"),
        ("line","hat"),
        ("live chat","canlı sohbet"),
        ("make arrangement","düzenleme yapmak"),
        ("make phone call","telefon etmek"),
        ("may I speak to","… ile konuşabilir miyim"),
        ("may I …","… yapabilir miyim"),
        ("meet","buluşmak"),
        ("memo","not, hatırlatma"),
        ("need","ihtiyaç duymak"),
        ("of course","tabii ki"),
        ("once upon a time","bir zamanlar"),
        ("overseas phone call","yurt dışı telefon görüşmesi"),
        ("polite","kibar"),
        ("possible","mümkün"),
        ("prefer","tercih etmek"),
        ("put through","telefona bağlamak"),
        ("reach information","bilgiye ulaşmak"),
        ("receiver","alıcı"),
        ("reminder","hatırlatıcı"),
        ("repeat","tekrarlamak"),
        ("replace","değiştirmek"),
        ("revolution","devrim"),
        ("ring","(telefon) çalmak, birini aramak"),
        ("send messages","mesaj göndermek"),
        ("shout","bağırmak"),
        ("smart phone","akıllı telefon"),
        ("soon","yakında"),
        ("study together","birlikte çalışmak"),
        ("sure","tabii"),
        ("take care","kendine iyi bak"),
        ("talk","konuşmak"),
        ("tell","söylemek"),
        ("text a message","mesaj yazmak"),
        ("the most","en çok"),
        ("try","denemek"),
        ("understand","anlamak"),
        ("want","istemek"),
        ("waste time","zaman harcamak"),
        ("way","yol, yöntem"),
        ("what’s wrong with you","senin neyin var"),
        ("who","kim"),
        ("with","ile"),
        ("without","-sız, -siz"),
        ("would you like to","ister misin"),
        ("write letter","mektup yazmak"),
        ("you are welcome","bir şey değil")

    ]
}
