unit5 = {
    "The Internet": [

        ("account","hesap"),
        ("addict","bağımlı"),
        ("adult","yetişkin"),
        ("advantage","avantaj"),
        ("advise","tavsiye etmek"),
        ("affect","etkilemek"),
        ("among","arasında"),
        ("application","uygulama"),
        ("attachment","ek dosya"),
        ("authorities","yetkililer"),
        ("become internet addict","internet bağımlısı olmak"),
        ("break relationship","ilişkiyi bitirmek"),
        ("broken","kırık, bozuk"),
        ("browse","göz atmak"),
        ("browser","tarayıcı"),
        ("busy","meşgul"),
        ("buy","satın almak"),
        ("by mistake","yanlışlıkla"),
        ("careful","dikkatli"),
        ("cause","sebep olmak"),
        ("cell phone","cep telefonu"),
        ("change","değiştirmek"),
        ("chat live","canlı sohbet etmek"),
        ("cheapest","en ucuz"),
        ("check cable","kabloyu kontrol etmek"),
        ("comment","yorum yapmak"),
        ("comment a post","bir gönderiye yorum yapmak"),
        ("communicate","iletişim kurmak"),
        ("confirm","onaylamak"),
        ("connect","bağlanmak"),
        ("connection","bağlantı"),
        ("contact","iletişime geçmek"),
        ("conversation","konuşma"),
        ("create content","içerik oluşturmak"),
        ("dangerous","tehlikeli"),
        ("delete","silmek"),
        ("detail","detay"),
        ("develop social skills","sosyal becerileri geliştirmek"),
        ("disadvantage","dezavantaj"),
        ("do research","araştırma yapmak"),
        ("download","indirmek"),
        ("easiest","en kolay"),
        ("feel isolated","yalnız hissetmek"),
        ("get information","bilgi almak"),
        ("give harm","zarar vermek"),
        ("go online","çevrimiçi olmak"),
        ("harmful","zararlı"),
        ("hour","saat"),
        ("ignore","görmezden gelmek"),
        ("important","önemli"),
        ("instant messaging","anlık mesajlaşma"),
        ("keep in touch with","…ile iletişimde kalmak"),
        ("leave a comment","yorum bırakmak"),
        ("letter","mektup"),
        ("log in","giriş yapmak"),
        ("log off","çıkış yapmak"),
        ("make life difficult","hayatı zorlaştırmak"),
        ("make new friends","yeni arkadaşlar edinmek"),
        ("make research","araştırma yapmak"),
        ("mean","anlamına gelmek, demek istemek"),
        ("meet strangers","yabancılarla tanışmak"),
        ("member","üye"),
        ("others","diğerleri"),
        ("password","şifre"),
        ("percent","yüzde"),
        ("phone call","telefon görüşmesi"),
        ("prefer","tercih etmek"),
        ("register","kaydolmak"),
        ("remember","hatırlamak"),
        ("reply","yanıt vermek"),
        ("reset","sıfırlamak"),
        ("safety","güvenlik"),
        ("screen","ekran"),
        ("search engine","arama motoru"),
        ("secret word","gizli kelime"),
        ("send","göndermek"),
        ("share personal information","kişisel bilgileri paylaşmak"),
        ("sign up","kayıt olmak"),
        ("sorry to hear that","bunu duyduğuma üzüldüm"),
        ("sounds good","kulağa hoş geliyor"),
        ("spend too much time","çok fazla zaman harcamak"),
        ("store","depolamak"),
        ("surf on internet","internette gezinmek"),
        ("take precaution","önlem almak"),
        ("teen","ergen"),
        ("teenager","genç"),
        ("tell","söylemek"),
        ("text","yazmak, metin"),
        ("text message","kısa mesaj yazmak"),
        ("upload","yüklemek"),
        ("upload pictures","resim yüklemek"),
        ("useful","faydalı"),
        ("useful purpose","faydalı amaç"),
        ("username","kullanıcı adı"),
        ("via","aracılığıyla"),
        ("want","istemek"),
        ("way","yol"),
        ("ways of communication","iletişim yolları")

    ]
}
