unit3 = {
    "In The Kitchen": [

        ("a pinch of salt","bir tutam tuz"),
        ("about","hakkında"),
        ("add","eklemek"),
        ("after that","bundan sonra"),
        ("another","başka"),
        ("bake","fırında pişirmek"),
        ("baking powder","kabartma tozu"),
        ("baking soda","karbonat"),
        ("baking tray","fırın tepsisi"),
        ("batter","hamur"),
        ("bean","fasulye"),
        ("beef","sığır eti"),
        ("boil","kaynatmak"),
        ("boiled","haşlanmış"),
        ("both sides","her iki taraf"),
        ("bowl","kase"),
        ("bread crumb","ekmek kırıntısı"),
        ("brush","fırçalamak"),
        ("butter","tereyağı"),
        ("cake tin","kek kalıbı"),
        ("cardamom powder","kakule tozu"),
        ("celery","kereviz"),
        ("chicken stock","tavuk suyu"),
        ("chop","doğramak"),
        ("chopped","doğranmış"),
        ("cinnamon","tarçın"),
        ("combine","birleştirmek"),
        ("cook","pişirmek"),
        ("corn starch","mısır nişastası"),
        ("cover","örtmek"),
        ("cumin","kimyon"),
        ("cut","kesmek"),
        ("cut in halves","ikiye bölmek"),
        ("describe process","süreci anlatmak, tarif etmek"),
        ("dessert","tatlı"),
        ("difficult","zor"),
        ("dice","küp küp doğramak"),
        ("dish","yemek, tabak"),
        ("dissolve","eritmek"),
        ("divide","bölmek"),
        ("drain","süzmek"),
        ("dough","hamur"),
        ("easy","kolay"),
        ("fill","doldurmak"),
        ("finally","sonunda"),
        ("first","ilk"),
        ("flour","un"),
        ("from","-den"),
        ("fry","kızartmak"),
        ("fridge","buzdolabı"),
        ("frying pan","kızartma tavası"),
        ("garlic","sarımsak"),
        ("get brown","kahverengileşmek"),
        ("get thick","kalınlaşmak"),
        ("grated","rendelenmiş"),
        ("grater","rende"),
        ("grill","ızgara yapmak"),
        ("high heat","yüksek ateş"),
        ("homemade bread","ev yapımı ekmek"),
        ("hour","saat"),
        ("how long","ne kadar süre"),
        ("how many","kaç tane"),
        ("how much","ne kadar"),
        ("how to make","nasıl yapılır"),
        ("indeed","gerçekten"),
        ("ingredients","malzemeler"),
        ("into","içine"),
        ("kitchen tools","mutfak gereçleri"),
        ("knead","yoğurmak"),
        ("knife","bıçak"),
        ("later","sonra"),
        ("large","büyük"),
        ("lemon juice","limon suyu"),
        ("lemon peel","limon kabuğu"),
        ("make dough","hamur yapmak"),
        ("make it rest","dinlendirmek"),
        ("mashed","ezilmiş"),
        ("meal","yemek"),
        ("medium heat","orta ateş"),
        ("melt the yeast","mayayı eritmek"),
        ("melted","eritilmiş"),
        ("method","yöntem"),
        ("minute","dakika"),
        ("minced beef","kıyma"),
        ("minced garlic","kıyılmış sarımsak"),
        ("mixture","karışım"),
        ("mussels","midye"),
        ("need","ihtiyaç duymak"),
        ("next","sonraki"),
        ("nut","fındık"),
        ("oiled","yağlanmış"),
        ("oven","fırın"),
        ("paella","deniz ürünlü ve tavuklu pilav (ispanyol yemeği)"),
        ("pan","tava"),
        ("paprika","kırmızı biber"),
        ("parsley","maydanoz"),
        ("pasta","makarna"),
        ("pepper","biber"),
        ("place","yerleştirmek"),
        ("plate","tabak"),
        ("pot","tencere"),
        ("pour","dökmek"),
        ("prawn","karides"),
        ("prefer","tercih etmek"),
        ("preheat","önceden ısıtmak"),
        ("preheated","önceden ısıtılmış"),
        ("prepare","hazırlamak"),
        ("preparation","hazırlık"),
        ("put","koymak"),
        ("raisin","kuru üzüm"),
        ("recipe","tarif"),
        ("red pepper flakes","kırmızı toz biber"),
        ("refrigerator","buzdolabı"),
        ("remember","hatırlamak"),
        ("remove","çıkarmak"),
        ("rinse","durulamak"),
        ("rise","kabarmak"),
        ("roast chicken","tavuk kızartmak"),
        ("rolling pin","oklava"),
        ("salt","tuz"),
        ("saffron","safran"),
        ("saucepan","tencere"),
        ("season","baharat eklemek"),
        ("second","ikinci"),
        ("seal the dumpling","mantıyı kapatmak"),
        ("serve","servis yapmak"),
        ("serve warm","sıcak servis yapmak"),
        ("set aside","bir kenara koymak"),
        ("shape","şekil"),
        ("sharp","keskin"),
        ("sheets of phyllo","yufka"),
        ("slice","dilim"),
        ("slightly","hafifçe"),
        ("smooth","pürüzsüz"),
        ("soak","ıslatmak, suda bekletmek"),
        ("spices","baharatlar"),
        ("spicy","baharatlı"),
        ("spoon","kaşık"),
        ("spread","yaymak"),
        ("sprinkle","serpmek"),
        ("square","kare"),
        ("starch","nişasta"),
        ("stir","karıştırmak"),
        ("strain","süzmek"),
        ("stretch","germek"),
        ("syrup","şerbet"),
        ("tasty","lezzetli"),
        ("temperature","sıcaklık"),
        ("tender","yumuşak"),
        ("then","sonra"),
        ("till","kadar"),
        ("top","üst"),
        ("tortilla","lavaş ekmeği"),
        ("tray","tepsi"),
        ("turn brown","kahverengileşmek"),
        ("until","-e kadar"),
        ("use","kullanmak"),
        ("vegetables","sebzeler"),
        ("whisk","çırpmak"),
        ("while","-iken"),
        ("with","ile")

    ]
}
