unit1 = {
    "Friendship": [

        ("about","hakkında"),
        ("accept","kabul etmek"),
        ("also","ayrıca"),
        ("although","rağmen"),
        ("always in a hurry","her zaman acele içinde"),
        ("always there for me","her zaman yanımda"),
        ("apologise","özür dilemek"),
        ("as soon as possible","mümkün olan en kısa sürede, bir an önce"),
        ("ask","sormak"),
        ("attend","katılmak"),
        ("back up","desteklemek"),
        ("become","olmak"),
        ("better","daha iyi"),
        ("boring","sıkıcı"),
        ("both","her ikisi de"),
        ("break promise","sözünden dönmek"),
        ("buddy","dost, kanka"),
        ("busy","meşgul"),
        ("call","aramak"),
        ("calm","sakin"),
        ("care","önemsemek, ilgilenmek"),
        ("caring","şefkatli"),
        ("choose","seçmek"),
        ("close friend","yakın arkadaş"),
        ("come over","uğramak"),
        ("concert","konser"),
        ("count on","güvenmek"),
        ("crazy","çılgın"),
        ("decide","karar vermek"),
        ("definition","tanım"),
        ("describe","tanımlamak"),
        ("different from","-den farklı"),
        ("dishonesty","dürüst olmama"),
        ("do you want","ister misin"),
        ("each other","birbirini"),
        ("excuse","bahane"),
        ("experience","deneyimlemek"),
        ("fair","adil"),
        ("fashionable","modaya uygun"),
        ("feel alone","yalnız hissetmek"),
        ("friendship","arkadaşlık"),
        ("full","tok, dolu"),
        ("fun","eğlenceli"),
        ("funny","komik"),
        ("generation","nesil"),
        ("get on well with each other","iyi geçinmek"),
        ("give advice","tavsiye vermek"),
        ("give","vermek"),
        ("guess","tahmin etmek"),
        ("guest","misafir"),
        ("have a lot in common","birçok ortak noktası olmak"),
        ("have nothing to do","yapacak bir şeyi olmamak"),
        ("honest","dürüst"),
        ("hope","ummak"),
        ("how about","ne dersin"),
        ("how is it going","nasıl gidiyor"),
        ("I would like to","isterim"),
        ("I’d love to","çok isterim"),
        ("idea","fikir"),
        ("important","önemli"),
        ("individual","bireysel"),
        ("instead","yerine"),
        ("interested in","ilgilenmek"),
        ("introduce","tanıştırmak"),
        ("invitation","davet"),
        ("invite","davet etmek"),
        ("keep promise","sözünü tutmak"),
        ("keep secret","sır tutmak"),
        ("laid back","rahat"),
        ("learn","öğrenmek"),
        ("letter","mektup"),
        ("lie","yalan"),
        ("like","gibi"),
        ("loyal","sadık"),
        ("loyalty","sadakat"),
        ("match","maç (eşleştirmek, kibrit)"),
        ("mate","arkadaş"),
        ("mean","anlamına gelmek"),
        ("meet","buluşmak"),
        ("movie theatre","sinema"),
        ("mutual respect","karşılıklı saygı"),
        ("mutual","karşılıklı"),
        ("need to","gerekmek"),
        ("need","ihtiyaç duymak"),
        ("neighbour","komşu"),
        ("not at all","hiç de değil, pek değil"),
        ("occupied","meşgul"),
        ("occur","meydana gelmek"),
        ("of course","tabii ki"),
        ("offer","teklif etmek"),
        ("others","diğerleri"),
        ("feeling","duygu"),
        ("priceless treasure","paha biçilmez hazine"),
        ("outgoing","dışa dönük"),
        ("patience","sabır"),
        ("patient","sabırlı"),
        ("personality","kişilik"),
        ("prefer","tercih etmek"),
        ("prepare snack","atıştırmalık hazırlamak"),
        ("priceless","paha biçilemez"),
        ("promise","söz vermek"),
        ("rarely","nadiren"),
        ("reason","sebep"),
        ("refuse","reddetmek"),
        ("relationship","ilişki"),
        ("relaxed","rahatlamış"),
        ("reliable","güvenilir"),
        ("rely on","güvenmek"),
        ("remain","kalmak"),
        ("respect","saygı"),
        ("respectful","saygılı"),
        ("same meaning","aynı anlam"),
        ("same opinion","aynı fikir"),
        ("same","aynı"),
        ("self-disciplined","öz disiplinli"),
        ("share","paylaşmak"),
        ("solemn","ciddi"),
        ("sorry I can’t","üzgünüm, yapamam"),
        ("sounds fun","kulağa eğlenceli geliyor"),
        ("sounds good/awesome","kulağa iyi/müthiş geliyor"),
        ("sounds great","kulağa harika geliyor"),
        ("spend time","zaman harcamak"),
        ("still","hala"),
        ("strong bond","güçlü bağ"),
        ("stuffed","tıka basa dolu"),
        ("support each other","birbirini desteklemek"),
        ("supportive","destekleyici"),
        ("sure","tabii ki"),
        ("survive","hayatta kalmak"),
        ("take things serious","ciddiye almak"),
        ("talk","konuşmak"),
        ("tell lie","yalan söylemek"),
        ("tell secret to others","başkalarına sır vermek"),
        ("tell","anlatmak"),
        ("text","mesaj yazmak"),
        ("that would be great","harika olurdu"),
        ("that’s why","bu yüzden"),
        ("thing","şey"),
        ("thirsty","susamış"),
        ("thrilling","heyecan verici, nefes kesici"),
        ("true friend","gerçek arkadaş"),
        ("trust","güvenmek"),
        ("unconditional","koşulsuz"),
        ("understand","anlamak"),
        ("want","istemek"),
        ("what about","ne dersin, peki ya …"),
        ("why not","neden olmasın"),
        ("would you like to","ister misin"),
        ("your own","kendinin, kendin")

    ]
}
