unit6 = {
    "Adventures": [

        ("absolutely","kesinlikle"),
        ("accept offer","teklifi kabul etmek"),
        ("addict","bağımlı"),
        ("adventure","macera"),
        ("afraid of","-den korkmak"),
        ("agree","katılmak"),
        ("air sports","hava sporları"),
        ("amazing","harika"),
        ("amused","eğlenmiş"),
        ("amusing","eğlenceli"),
        ("barefoot walking","çıplak ayakla yürüme"),
        ("boring","sıkıcı"),
        ("build construction","inşaat yapmak"),
        ("bungee jumping","yüksekten esnek bir iple atlama"),
        ("can’t stand","hiç sevmemek, katlanamamak"),
        ("canoeing","kano sporu"),
        ("cave","mağara"),
        ("caving","mağaracılık"),
        ("challenging","zorlayıcı"),
        ("climb","tırmanmak"),
        ("crazy","çılgın"),
        ("cycling","bisiklet sürme"),
        ("dangerous","tehlikeli"),
        ("describe","tanımlamak"),
        ("describe experience","deneyimi tanımlamak"),
        ("desert","çöl"),
        ("device","cihaz"),
        ("disagree","katılmamak"),
        ("disappointing","hayal kırıklığına uğratan"),
        ("diving suit","dalış kıyafeti"),
        ("enjoyable","keyifli"),
        ("entertain","eğlendirmek"),
        ("entertaining","eğlenceli"),
        ("equipment","ekipman"),
        ("excitement","heyecan"),
        ("exciting","heyecan verici"),
        ("experience","deneyim"),
        ("explore","keşfetmek"),
        ("explore underwater","su altını keşfetmek"),
        ("extreme sports","uç/tehlikeli sporlar"),
        ("fall down","düşmek"),
        ("famous","ünlü"),
        ("famous places","ünlü yerler"),
        ("fascinating","büyüleyici"),
        ("feel the wind","rüzgarı hissetmek"),
        ("fight with waves","dalgalarla mücadele etmek"),
        ("float in the air","havada süzülmek"),
        ("fond of","düşkün olmak"),
        ("get on expedition","keşif gezisine çıkmak"),
        ("googles","koruyucu gözlükler"),
        ("guess","tahmin etmek"),
        ("hang around","takılmak"),
        ("hang gliding","yamaç paraşütü"),
        ("have something in common","ortak bir şeye sahip olmak"),
        ("height","yükseklik"),
        ("helmet","kask"),
        ("high","yüksek"),
        ("high place","yüksek yer"),
        ("high tower","yüksek kule"),
        ("hiking","doğa yürüyüşü"),
        ("historical site","tarihi alan"),
        ("hot air balloon","sıcak hava balonu"),
        ("ice climbing","buz tırmanışı"),
        ("impressive","etkileyici"),
        ("incredible","inanılmaz"),
        ("interesting","ilginç"),
        ("involve","içermek"),
        ("kayaking","kano yapma"),
        ("knee pad","dizlik"),
        ("land sports","kara sporları"),
        ("less","daha az"),
        ("make a change","bir değişiklik yapmak"),
        ("mean","anlamına gelmek, kastetmek"),
        ("meet sea creatures","deniz canlılarıyla tanışmak"),
        ("motor racing","motor yarışı"),
        ("nature","doğa"),
        ("offer","teklif"),
        ("on my own","kendi başıma"),
        ("other","diğer"),
        ("outdoor activities","açık hava aktiviteleri"),
        ("over","üzerinde"),
        ("paragliding","yamaç paraşütü"),
        ("parasailing","deniz paraşütü"),
        ("parkour","parkur sporu"),
        ("prefer","tercih etmek"),
        ("push limits","sınırları zorlamak"),
        ("rare","nadir"),
        ("reason","sebep"),
        ("robber boat","şişme bot"),
        ("rocky surface","kayalık yüzey"),
        ("rough water","dalgalı su"),
        ("row","kürek çekmek"),
        ("sailing","yelken sporu"),
        ("sand kiting","kum sörfü"),
        ("scenery","manzara"),
        ("scuba diving","tüplü dalış"),
        ("skateboarding","kaykay"),
        ("skiing","kayak"),
        ("skyscraper","gökdelen"),
        ("so far","şimdiye kadar"),
        ("special breathing equipment","özel solunum ekipmanı"),
        ("special track","özel parkur"),
        ("speed","hız"),
        ("spend time","vakit geçirmek"),
        ("take risk","risk almak"),
        ("the most","en çok"),
        ("think","düşünmek"),
        ("tied","bağlı"),
        ("top of a hill","tepenin zirvesi"),
        ("top of a mountain","dağın zirvesi"),
        ("travel","seyahat etmek"),
        ("trekking","doğa yürüyüşü"),
        ("try","denemek"),
        ("under","altında"),
        ("unpowered aircraft","motorsuz hava aracı"),
        ("watch scenery","manzarayı izlemek"),
        ("wingsuit skydiving","kanatlı elbiseyle uçma"),
        ("winter sports","kış sporları"),
        ("wooden","ahşap"),
        ("would like to","istemek"),
        ("would rather","tercih etmek"),
        ("ziplining","çelik halatla iniş")

    ]
}
