unit9 = {
    "Science": [

        ("accept","kabul etmek"),
        ("achievement","başarı"),
        ("add","eklemek"),
        ("admire","hayran olmak"),
        ("admire struggle","mücadeleye hayran olmak"),
        ("adventure","macera"),
        ("allow","izin vermek"),
        ("amazing","harika"),
        ("ancient","antik"),
        ("apologize","özür dilemek"),
        ("appreciate","takdir etmek"),
        ("become famous","ünlü olmak"),
        ("begin","başlamak"),
        ("borrow","ödünç almak"),
        ("brilliant","parlak"),
        ("bring","getirmek"),
        ("busy","meşgul"),
        ("calculator","hesap makinesi"),
        ("carry","taşımak"),
        ("change","değiştirmek"),
        ("change the world","dünyayı değiştirmek"),
        ("childhood","çocukluk"),
        ("claim","iddia etmek"),
        ("communication","iletişim"),
        ("compass","pusula"),
        ("conduct experiment","deney yapmak"),
        ("cover","örtmek"),
        ("create","yaratmak"),
        ("currently","şu anda"),
        ("dangerous","tehlikeli"),
        ("describe","tanımlamak"),
        ("deserve","hak etmek"),
        ("design","tasarlamak"),
        ("develop","geliştirmek"),
        ("develop cure","tedavi geliştirmek"),
        ("diagnose","teşhis etmek"),
        ("die","ölmek"),
        ("difficult","zor"),
        ("dine","akşam yemeği yemek"),
        ("disadvantage","dezavantaj"),
        ("discover","keşfetmek"),
        ("discoverer","kaşif"),
        ("discovery","keşif"),
        ("disease","hastalık"),
        ("do research","araştırma yapmak"),
        ("documentaries","belgeseller"),
        ("earth","dünya"),
        ("education","eğitim"),
        ("electric bulb","elektrik ampulü"),
        ("engineering","mühendislik"),
        ("entertainment","eğlence"),
        ("examine","incelemek"),
        ("experiment","deney"),
        ("explore","keşfetmek"),
        ("explorer","kaşif"),
        ("fact","gerçek"),
        ("famous","ünlü"),
        ("find out","öğrenmek"),
        ("forever","sonsuzca"),
        ("forget","unutmak"),
        ("gain knowledge","bilgi edinmek"),
        ("genius","dahi"),
        ("get better","iyileşmek"),
        ("get treated","tedavi olmak"),
        ("goldsmith","kuyumcu"),
        ("happen","olmak"),
        ("heal infection","enfeksiyonu iyileştirmek"),
        ("healthcare cost","sağlık masrafları"),
        ("heat test tube","deney tüpünü ısıtmak"),
        ("human","insan"),
        ("idea","fikir"),
        ("improve","geliştirmek"),
        ("improvement","gelişim"),
        ("incredible","inanılmaz"),
        ("information","bilgi"),
        ("insist on","ısrar etmek"),
        ("instead of","yerine"),
        ("interested","ilgili"),
        ("invent","icat etmek"),
        ("invention","icat"),
        ("inventor","mucit"),
        ("journalist","gazeteci"),
        ("lab","laboratuvar"),
        ("leave","ayrılmak"),
        ("lend","ödünç vermek"),
        ("lift","kaldırmak"),
        ("live","yaşamak"),
        ("look for","aramak"),
        ("loud","yüksek sesle"),
        ("make calculation","hesaplama yapmak"),
        ("make experiment","deney yapmak"),
        ("masterpiece","başyapıt"),
        ("matter","madde"),
        ("mean","anlamına gelmek"),
        ("milestone","dönüm noktası"),
        ("moveable","taşınabilir"),
        ("need to","gerekmek"),
        ("novel","roman"),
        ("observe","gözlemlemek"),
        ("observe substances","maddeleri gözlemlemek"),
        ("operate machine","makineyi çalıştırmak"),
        ("orbit the sun","güneşin etrafında dönmek"),
        ("other","diğer"),
        ("paint","boyamak"),
        ("pass away","vefat etmek"),
        ("patience","sabır"),
        ("physic","fizik"),
        ("place","yerleştirmek"),
        ("poem","şiir"),
        ("poetry","şiir sanatı"),
        ("prepare","hazırlamak"),
        ("print","yazdırmak"),
        ("printing press","matbaa"),
        ("process","işlem"),
        ("prototype","ilk örnek, prototip"),
        ("publish","yayımlamak"),
        ("radio waves","radyo dalgaları"),
        ("reach","ulaşmak"),
        ("realize","farkına varmak"),
        ("reason","sebep"),
        ("record","kaydetmek"),
        ("reduce","azaltmak"),
        ("reject","reddetmek"),
        ("related with","ile ilgili"),
        ("replace","yerine koymak"),
        ("research","araştırmak"),
        ("result","sonuç"),
        ("revolutionary","devrim niteliğinde"),
        ("science","bilim"),
        ("science fiction","bilim kurgu"),
        ("scientific","bilimsel"),
        ("scientist","bilim insanı"),
        ("search","aramak"),
        ("send","göndermek"),
        ("servant","hizmetçi"),
        ("share information","bilgi paylaşmak"),
        ("smartphone","akıllı telefon"),
        ("soon","yakında"),
        ("space","uzay"),
        ("space travel","uzay yolculuğu"),
        ("spin on its axis","kendi ekseni etrafında dönmek"),
        ("spread","yayılmak"),
        ("store information","bilgiyi depolamak"),
        ("strange","garip"),
        ("structure of DNA","DNA’nın yapısı"),
        ("struggle","mücadele etmek"),
        ("study law","hukuk eğitimi almak"),
        ("survive","hayatta kalmak"),
        ("telegram","telgraf"),
        ("tell","söylemek"),
        ("thanks to","sayesinde"),
        ("that’s why","bu yüzden"),
        ("thing","şey"),
        ("treatment","tedavi"),
        ("type","yazmak"),
        ("typewriter","daktilo"),
        ("unbearable","dayanılmaz"),
        ("unique","benzersiz"),
        ("universe","evren"),
        ("use","kullanmak"),
        ("vaccination","aşı"),
        ("widen people’s horizon","insanların ufkunu genişletmek"),
        ("wonder","merak etmek"),
        ("writer","yazar")

    ]
}
