unit10 = {
    "Natural Forces": [

        ("absence","yokluk"),
        ("acre","dönüm"),
        ("after shock","artçı sarsıntı"),
        ("agree","katılmak"),
        ("agriculture","tarım"),
        ("air pollution","hava kirliliği"),
        ("animal species","hayvan türleri"),
        ("ash","kül"),
        ("authorities","yetkililer"),
        ("avalanche","çığ"),
        ("blow","esmek"),
        ("blow off","uçurmak"),
        ("cause","sebep olmak"),
        ("climate","iklim"),
        ("climate change","iklim değişikliği"),
        ("collapse building","binayı yıkmak"),
        ("country","ülke"),
        ("crops","mahsuller"),
        ("damage","zarar vermek"),
        ("damaged","hasar görmüş"),
        ("dangerous","tehlikeli"),
        ("deal with","başa çıkmak"),
        ("death","ölüm"),
        ("deforestation","ormansızlaşma"),
        ("destroy","yok etmek"),
        ("destroy forest","ormanı yok etmek"),
        ("disagree","katılmamak"),
        ("drought","kuraklık"),
        ("dry weather","kuru hava"),
        ("during","sırasında"),
        ("earth’s crust","dünya kabuğu"),
        ("earthquake","deprem"),
        ("educate people","insanları eğitmek"),
        ("enough","yeterli"),
        ("environment","çevre"),
        ("escape","kaçmak"),
        ("evolve into","evrilmek"),
        ("extreme heat","aşırı sıcak"),
        ("factories","fabrikalar"),
        ("fall","düşmek"),
        ("fatal","ölümcül"),
        ("first aid","ilk yardım"),
        ("flood","sel"),
        ("flooding","sel baskını"),
        ("flow down","aşağı akmak"),
        ("future","gelecek"),
        ("global warming","küresel ısınma"),
        ("government","hükümet"),
        ("greenhouse gases","sera gazları"),
        ("grow crops","mahsul yetiştirmek"),
        ("guess","tahmin etmek"),
        ("happen","olmak"),
        ("harm environment","çevreye zarar vermek"),
        ("hill","tepe"),
        ("hit the city","şehri vurmak"),
        ("huge flames","dev alevler"),
        ("human","insan"),
        ("human being","insan"),
        ("hurricane","kasırga"),
        ("increase","artırmak"),
        ("information","bilgi"),
        ("injury","yaralanma"),
        ("interested in","ile ilgilenmek"),
        ("keep on","devam etmek"),
        ("kill","öldürmek"),
        ("lack","eksiklik"),
        ("land","arazi"),
        ("land slide","toprak kayması"),
        ("lead to","yol açmak"),
        ("leave","ayrılmak"),
        ("less","daha az"),
        ("lightning","yıldırım"),
        ("liquid","sıvı"),
        ("loss of harvest","ürün kaybı"),
        ("make heavy things immobilize","ağır şeyleri hareketsiz hale getirmek"),
        ("mean","anlamına gelmek"),
        ("melt","erimek"),
        ("molten rock","erimiş kaya"),
        ("mountain","dağ"),
        ("movement","hareket"),
        ("mud","çamur"),
        ("natural disasters","doğal afetler"),
        ("natural forces","doğal kuvvetler"),
        ("occur","meydana gelmek"),
        ("ocean","okyanus"),
        ("past","geçmiş"),
        ("planet","gezegen"),
        ("plant","bitki"),
        ("prepare","hazırlamak"),
        ("prevent","önlemek"),
        ("produce","üretmek"),
        ("produce clean energy","temiz enerji üretmek"),
        ("rain","yağmur"),
        ("reduce","azaltmak"),
        ("rescue team","kurtarma ekibi"),
        ("result","sonuç"),
        ("river","nehir"),
        ("roof","çatı"),
        ("run out of oxygen","oksijenin tükenmesi"),
        ("safe","güvenli"),
        ("save","kurtarmak"),
        ("shake","sallamak"),
        ("shortage","kıtlık"),
        ("snow","kar"),
        ("solid","katı"),
        ("speed","hız"),
        ("spread","yayılmak"),
        ("starvation","açlık"),
        ("stay away","uzak durmak"),
        ("storm","fırtına"),
        ("strong","güçlü"),
        ("strong buildings","sağlam binalar"),
        ("stuck under debris","enkaz altında sıkışmak"),
        ("sudden","ani"),
        ("suffer from","-den muzdarip olmak"),
        ("suggestion","öneri"),
        ("surface","yüzey"),
        ("swallow","yutmak"),
        ("take care","ilgilenmek"),
        ("take precaution","önlem almak"),
        ("take short shower","kısa duş almak"),
        ("temperature","sıcaklık"),
        ("terrible","korkunç"),
        ("think","düşünmek"),
        ("threaten the earth","dünyayı tehdit etmek"),
        ("tornado","kasırga"),
        ("unbelievable","inanılmaz"),
        ("uncontrollable","kontrol edilemez"),
        ("vegetation","bitki örtüsü"),
        ("volcanic eruption","volkanik patlama"),
        ("warm up","ısınmak"),
        ("warn","uyarmak"),
        ("waste","israf etmek"),
        ("waste water","su israf etmek"),
        ("water shortage","su kıtlığı"),
        ("wave","dalga"),
        ("wild fire","orman yangını"),
        ("wind","rüzgar"),
        ("wipe out","yok etmek")

    ]
}
