unit8 = {
    "Chores": [

        ("adult","yetişkin"),
        ("all","hepsi"),
        ("annoy","rahatsız etmek"),
        ("article","makale"),
        ("ask","sormak"),
        ("become","olmak"),
        ("both","her ikisi"),
        ("busy with","ile meşgul"),
        ("chores","ev işleri"),
        ("classroom rules","sınıf kuralları"),
        ("clean","temiz"),
        ("clean up","temizlemek"),
        ("complain","şikayet etmek"),
        ("cook meal","yemek pişirmek"),
        ("correct","düzeltmek"),
        ("describe","tanımlamak"),
        ("difficult","zor"),
        ("dirty","kirli"),
        ("dirty clothes","kirli kıyafetler"),
        ("do chores","ev işleri yapmak"),
        ("do errands","ayak işleri yapmak"),
        ("do household chores","ev işleri yapmak"),
        ("do laundry","çamaşır yıkamak"),
        ("do shopping","alışveriş yapmak"),
        ("do the ironing","ütü yapmak"),
        ("dry the dishes","bulaşıkları kurutmak"),
        ("dust the furniture","mobilyaları toz almak"),
        ("duty","görev"),
        ("each other","birbirleri"),
        ("easy","kolay"),
        ("elder","yaşlı"),
        ("empty dishwasher","bulaşık makinesini boşaltmak"),
        ("everyone","herkes"),
        ("express obligation","zorunluluğu ifade etmek"),
        ("feed the pet","evcil hayvanı beslemek"),
        ("feel","hissetmek"),
        ("fork","çatal"),
        ("get worried","endişelenmek"),
        ("give","vermek"),
        ("guess","tahmin etmek"),
        ("hard","zor"),
        ("have responsibilities","sorumluluklara sahip olmak"),
        ("have strong ties","güçlü bağlara sahip olmak"),
        ("have to","zorunda olmak"),
        ("healthy","sağlıklı"),
        ("help parents","ebeveynlere yardım etmek"),
        ("housework","ev işi"),
        ("important","önemli"),
        ("in charge of","sorumlu"),
        ("iron clothes","kıyafetleri ütülemek"),
        ("keep room tidy","odayı düzenli tutmak"),
        ("knife","bıçak"),
        ("learn","öğrenmek"),
        ("lesson","ders"),
        ("let","izin vermek"),
        ("load dishwasher","bulaşık makinesini doldurmak"),
        ("main idea","ana fikir"),
        ("make life easier","hayatı kolaylaştırmak"),
        ("make the bed","yatağı toplamak"),
        ("meal","öğün"),
        ("member","üye"),
        ("mess","dağınıklık"),
        ("mind","önemsemek"),
        ("mop the floor","yerleri paspaslamak"),
        ("must","-meli/-malı"),
        ("necessary","gerekli"),
        ("need","ihtiyaç duymak"),
        ("obey rule","kurala uymak"),
        ("obligation","zorunluluk"),
        ("peaceful","huzurlu"),
        ("plate","tabak"),
        ("pocket money","harçlık"),
        ("prepare","hazırlamak"),
        ("promise","söz vermek"),
        ("put plates on table","masaya tabak koymak"),
        ("respect","saygı göstermek"),
        ("respect right","hakka saygı göstermek"),
        ("respectful","saygılı"),
        ("responsibility","sorumluluk"),
        ("responsible","sorumlu"),
        ("responsible for","-den sorumlu"),
        ("right","hak"),
        ("rude","kaba"),
        ("same","aynı"),
        ("say","söylemek"),
        ("set table","masayı kurmak"),
        ("share opinion","fikir paylaşmak"),
        ("share responsibilities","sorumlulukları paylaşmak"),
        ("show respect to each other","birbirine saygı göstermek"),
        ("take care of garden","bahçeyle ilgilenmek"),
        ("take out garbage","çöpü dışarı çıkarmak"),
        ("task","görev"),
        ("tell","söylemek"),
        ("think","düşünmek"),
        ("tidy up room","odayı toparlamak"),
        ("to do list","yapılacaklar listesi"),
        ("vacuum carpet","halıyı süpürmek"),
        ("vacuum floor","zemini süpürmek"),
        ("walk the dog","köpeği gezdirmek"),
        ("wash","yıkamak"),
        ("wash the dishes","bulaşıkları yıkamak"),
        ("work harder","daha çok çalışmak"),
        ("young","genç")

    ]
}
