unit2 = {
    "Teen Life": [

        ("about","hakkında"),
        ("admire","hayran olmak"),
        ("adult","yetişkin"),
        ("advise","tavsiye vermek"),
        ("always","her zaman"),
        ("amazing","şaşırtıcı"),
        ("among teenagers","gençler arasında"),
        ("argue","tartışmak"),
        ("art club","sanat kulübü"),
        ("band","müzik grubu"),
        ("buy","satın almak"),
        ("can’t stand","katlanamamak"),
        ("casual clothes","günlük kıyafetler, rahat kıyafetler"),
        ("chat","sohbet etmek"),
        ("cheap","ucuz"),
        ("choose","seçmek"),
        ("come over","uğramak"),
        ("comfortable","rahat"),
        ("concert","konser"),
        ("conversation","sohbet"),
        ("different","farklı"),
        ("do exercise","egzersiz yapmak"),
        ("documentaries","belgeseller"),
        ("drummer","davulcu"),
        ("each other","birbirini"),
        ("easily","kolayca"),
        ("easy","kolay"),
        ("educational","eğitici"),
        ("educative","öğretici"),
        ("enjoy","keyif almak"),
        ("enjoyable","keyifli"),
        ("enlarge horizon","ufkunu genişletmek"),
        ("event","etkinlik"),
        ("everywhere","her yerde"),
        ("express","ifade etmek"),
        ("fashion","moda"),
        ("fast","hızlı"),
        ("follow","takip etmek"),
        ("fond of","düşkün"),
        ("for example","örneğin"),
        ("form a band","bir müzik grubu kurmak"),
        ("free time","boş zaman"),
        ("good relationship","iyi ilişki"),
        ("gym","spor salonu"),
        ("hang around","takılmak, gezinmek"),
        ("hang out","vakit geçirmek"),
        ("hate","nefret etmek"),
        ("healthy","sağlıklı"),
        ("hiking","doğa yürüyüşü"),
        ("historical","tarihi"),
        ("impressive","etkileyici"),
        ("individual sport","bireysel spor"),
        ("keen on","meraklı"),
        ("kind","nazik"),
        ("latest","en son"),
        ("loud","yüksek sesli"),
        ("more or less","aşağı yukarı"),
        ("most of the time","çoğu zaman"),
        ("mostly","çoğunlukla"),
        ("national","ulusal"),
        ("no way","olmaz, asla"),
        ("patriot","vatansever"),
        ("personal opinion","kişisel görüş"),
        ("prefer","tercih etmek"),
        ("rarely","nadiren"),
        ("reach","ulaşmak"),
        ("recommend","tavsiye etmek"),
        ("relaxing","rahatlatıcı"),
        ("rest","dinlenmek"),
        ("same","aynı"),
        ("science fiction","bilim kurgu"),
        ("seldom","seyrek"),
        ("send","göndermek"),
        ("smart clothes","şık kıyafetler"),
        ("snob","züppe"),
        ("sometimes","bazen"),
        ("spend time","zaman geçirmek"),
        ("suggest","önermek"),
        ("talk about","hakkında konuşmak"),
        ("team sport","takım sporu"),
        ("teenagers","gençler"),
        ("terrific","müthiş"),
        ("text","mesaj atmak"),
        ("that’s why","bu yüzden"),
        ("things","şeyler"),
        ("think","düşünmek"),
        ("ticket","bilet"),
        ("to be honest","dürüst olmak gerekirse"),
        ("train in the field","sahada antrenman yapmak"),
        ("trendy","moda olan"),
        ("type","tür"),
        ("unbearable","dayanılmaz"),
        ("usually","genellikle"),
        ("wear","giymek"),
        ("weather","hava durumu"),
        ("weekend","hafta sonu"),
        ("what about","ne dersin, peki ya…"),
        ("what kind of","ne tür"),
        ("what type of","ne tür"),
        ("while","iken"),
        ("work out","spor yapmak"),
        ("youth stories","gençlik hikayeleri")

    ]
}
